### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR",
  "developerSkillType": "FULL_STACK",
  "experienceYears": 10,
  "memberId": "Mini",
  "name": "mouse Kim",
  "age": 20
}